### ISSUE TITLE
kubeflow-roles failed to upgrade 1.6 to 1.7

### ISSUE THREAD

**Issue by i-chvets** [canonical/kubeflow-roles-operator#40]
Failed to reach active/idle:

kubeflow-roles stuck in maintenance

This could be easy check, because charm does not report errors.

[Jira](https://warthogs.atlassian.net/browse/KF-1108)

**Comment by DnPlas** [comment]
Hi @i-chvets, I was not able to reproduce this issue by deploying `kubeflow-roles 1.6/stable` and refreshing to `kubeflow-roles latest/stable`. Here is the output of `juju status` after refreshing:

```
ubuntu@ip-172-31-13-175:~$ juju status kubeflow-roles
Model     Controller  Cloud/Region        Version  SLA          Timestamp
kubeflow  uk8s        microk8s/localhost  2.9.34   unsupported  11:16:49Z

App             Version  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
kubeflow-roles           active      1  kubeflow-roles  latest/edge   97  10.152.183.105  no       

Unit               Workload  Agent  Address      Ports  Message
kubeflow-roles/0*  active    idle   10.1.216.16  
```

If you provide steps to reproduce and some logs, we can dig deeper into this.

**Comment by i-chvets** [comment]
Works. Verified in latest upgrade.
