### ISSUE TITLE
1.7.1 pre-release testing : charm stuck in blocked state during upgrade 1.6 to 1.7.1

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kubeflow-roles-operator#54]
To reproduce:
- deploy kubeflow-roles 1.6/stable
- juju remove-application kubeflow-roles
- juju deploy kubeflow-roles --channel 1.7/edge

Message:
```
There were 29 errors while applying manifests. Do you need to run 'juju trust kubeflow-roles'?
```
Logs:
```
INFO juju-log Running legacy hooks/install.
[pebble] Check "readiness" failure 1 (threshold 3): received non-20x status code 418
[container-agent] 2023-06-09 11:10:58 ERROR juju-log clusterroles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:kubeflow:kubeflow-roles" cannot create resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
```
Workaround: run `juju trust kubeflow-roles --scope=cluster` as suggested in the message

**Comment by ca-scribner** [comment]
`kubeflow-roles` for 1.6 needed `--trust` as well.  Is there a reason why we deploy it first without?

Although I'm surprised `kubeflow-roles` 1.6 without `--trust` didn't give an error message

**Comment by ca-scribner** [comment]
Yeah to reproduce, I think you just need to do:
* `juju deploy kubeflow-roles --channel 1.6/stable` (no `--trust`).  

iiuc, the only issue here is that trust is missing, and not related to removing and redeploying
